README.zh-cn.md
=> fix spelling mistake

README.md
=> Small fix the example URL

README.ja.md, README.ko.md, README.md, README.zh-cn.md
This command removes merged branches.
=> Add git cleanup alias

README.ja.md
=> Update Ja translation to 086595f

README.zh-cn.md
=> Update zh-cn translations to ea4fc85

README.md
a good visual way to learn and understand git concepts
=> add useful git resource

README.ja.md
=> Update Ja translation to 3c21657

README.ja.md, README.ko.md, README.md, README.zh-cn.md, README.zh-tw.md
modify zh-cn locale to zh-tw locale
=> add zh-tw locale

README.md
[Rendered README](https://github.com/tiimgreen/github-cheat-sheet/blob/67da27756284b95bd956413d21122b7c16eef3d1/README.md#rendering-pdf)
=> Add Rendering PDF

README.ja.md, README.ko.md, README.zh-cn.md
=> Fixes non-Eng versions for #126

README.md
=> Adding SSH key trick

README.zh-tw.md
cc @tiimgreen 
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
=> Add ssh keys and git grep section in chinese traditional version.

README.ko.md
- also change all 깃허브 to Github. (related #145)
=> Update Korean translation to ac2d48f

README.md
* adds Learn Git Branching
* adds some videos
* adds .gitignore templates
* adds article section and updates menu
=> adds some more resources

README.ko.md
Also updated words:
- 깃 → Git
- 익스텐션 → 확장 프로그램
- 푸쉬 → 푸시
- 디랙토리 → 디렉터리
- 메세지 → 메시지
- 레포지터리 → 저장소
- 커맨트 → 댓글
- 레일즈 → 레일스
- 케쉬 → 캐시
- 신텍스 → 신택스
- 테스크 리스트 → 할 일 목록
- 컨텐츠 → 콘텐츠
- 데이타 → 데이터
- 풀리퀘스트 → 풀 리퀘스트
- 핼퍼 → 헬퍼
- 포멧 → 포맷
- 플레그 → 플래그
=> Update Korean translation to 21e084d

README.ko.md
=> Update Korean translation to b85d914

.travis.yml
This pull requests updates .travis.yml
- move white list items into a `wl` variable so it can be reused
- add `vimeo` to white list
- improve formatting to be more readable
=> [ci] improve travis.yml

README.md
Made a few changes that I thought made the README more readable.
=> Minor format-change suggestions for README.md

README.ja.md, README.ko.md, README.md, README.zh-cn.md, README.zh-tw.md
=> Fix a error Markdown format in Aliases section

README.md
Provide more details for the git feature auto-correct.
=> Improve git auto-correct

README.md
I would like to add my blog post to this (awesome) cheat-sheet list :)
=> Add GitHub Resources - GitHub Best Practices

README.md
I don't see any documentation for this feature but its been around for awhile.
```
https://github.com/{user}.png
```
=> Add section for "Profile Image"
